version: '3.8'

services:
  my_api:
    image: focustrack_api:latest
    build: .
    container_name: focustrack-backend-api
    ports:
      - "3000:3000"
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    networks:
      - my_network
    depends_on:
      - mosquitto
    environment:
      - NODE_ENV=development
      - PORT=3000

  mosquitto:
    image: eclipse-mosquitto
    container_name: mosquitto_broker
    ports:
      - "1883:1883"
      - "8000:8000"
    volumes:
      - ./mosquitto.conf:/mosquitto/config/mosquitto.conf
    networks:
      - my_network

networks:
  my_network:
    driver: bridge
