// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCykArCTwCWN72kxRLvBj4SyN9BrYmXxhU',
    appId: '1:419951005838:web:00ae5ba6f056a2a18af9df',
    messagingSenderId: '419951005838',
    projectId: 'focustrack-cd465',
    authDomain: 'focustrack-cd465.firebaseapp.com',
    storageBucket: 'focustrack-cd465.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAJivsfLHzcTG0VpMil1VA7xqfodBSaPVs',
    appId: '1:419951005838:android:9815fd82f54656d28af9df',
    messagingSenderId: '419951005838',
    projectId: 'focustrack-cd465',
    storageBucket: 'focustrack-cd465.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBvu7NEAdUJHHUaHZWE0yzXOp8PHTqet9g',
    appId: '1:419951005838:ios:32ded5839e38b3e88af9df',
    messagingSenderId: '419951005838',
    projectId: 'focustrack-cd465',
    storageBucket: 'focustrack-cd465.firebasestorage.app',
    iosBundleId: 'com.example.focusTrack2',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBvu7NEAdUJHHUaHZWE0yzXOp8PHTqet9g',
    appId: '1:419951005838:ios:32ded5839e38b3e88af9df',
    messagingSenderId: '419951005838',
    projectId: 'focustrack-cd465',
    storageBucket: 'focustrack-cd465.firebasestorage.app',
    iosBundleId: 'com.example.focusTrack2',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCykArCTwCWN72kxRLvBj4SyN9BrYmXxhU',
    appId: '1:419951005838:web:256b60dc2762d4728af9df',
    messagingSenderId: '419951005838',
    projectId: 'focustrack-cd465',
    authDomain: 'focustrack-cd465.firebaseapp.com',
    storageBucket: 'focustrack-cd465.firebasestorage.app',
  );
}
